<a href="https://colab.research.google.com/github/engmohamedsalah/AIMaster/blob/master/Linear_Algebra_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. Load libraries and create a matrix

In [1]:
%matplotlib inline
import sympy as sympy
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn
from scipy import *

In [3]:
x = .5
print(x)

0.5


In [4]:
x_vector = np.array([1,2,3])
print(x_vector)


[1 2 3]


In [5]:
c_list = [1,2]
print("The list:",c_list)
print("Has length:", len(c_list))

c_vector = np.array(c_list)
print("The vector:", c_vector)
print("Has shape:",c_vector.shape)

The list: [1, 2]
Has length: 2
The vector: [1 2]
Has shape: (2,)


In [6]:
z = [5,6]
print("This is a list, not an array:",z)
print(type(z))


zarray = np.array(z)
print("This is an array, not a list",zarray)
print(type(zarray))


This is a list, not an array: [5, 6]
<class 'list'>
This is an array, not a list [5 6]
<class 'numpy.ndarray'>


In [7]:
b = list(zip(z,c_vector))
print(b)

[(5, 1), (6, 2)]


In [10]:
A = np.array(b)
print( A)
print( type(A))
print( "A has shape:",A.shape)

[[5 1]
 [6 2]]
<class 'numpy.ndarray'>
A has shape: (2, 2)


# 2. Conduct matrix addition and subtraction

In [21]:
A = np.array([[2, 3], [4, 5]])

In [22]:
type(A)

numpy.ndarray

In [25]:
print(A + 3)

[[5 6]
 [7 8]]


In [26]:
print(3 + A)

[[5 6]
 [7 8]]


In [27]:
B= np.array([[20,30],[40,50]])

In [28]:
print(A+B)

[[22 33]
 [44 55]]


In [29]:
print(A-B)

[[-18 -27]
 [-36 -45]]


#3. Conduct matrix multiplication and division

In [30]:
print(A*3)

[[ 6  9]
 [12 15]]


In [34]:
C= np.array([[4,5,3],[1,3,4]])
print(A@C)

[[11 19 18]
 [21 35 32]]


In [36]:
print(A/B)

[[0.1 0.1]
 [0.1 0.1]]


 matrix transpose

In [41]:
print(A)
print("--------")
print(A.T)


[[2 3]
 [4 5]]
--------
[[2 4]
 [3 5]]


In [48]:
testing = np.arange(6).reshape((3,2))

In [49]:
print(testing)

[[0 1]
 [2 3]
 [4 5]]


In [52]:
A.dot(B)

array([[160, 210],
       [280, 370]])